### ISSUE TITLE
update gabc documentation

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio-project.github.io#77]
On [this page](http://gregorio-project.github.io/gabc/index.html), the deprecated `initial-style` is still in use, maybe a few other properties are too. See https://github.com/gregorio-project/gregorio/issues/1432

**Comment by rpspringuel** [comment]
Fixed by 1489a66fb1cd69e79a7efb7ba09df86c053273a2.

**Comment by SirPL** [comment]
`initial-style` is still present on the website linked in the first comment:
![image](https://user-images.githubusercontent.com/11311649/107754941-7ab61100-6d22-11eb-91f2-db333570b8d0.png)

`initial-style` is also mentioned in the GregorioRef (as of v5.2.1)
![image](https://user-images.githubusercontent.com/11311649/107755173-c2d53380-6d22-11eb-92b2-1b3452bbcd32.png)

**Comment by rpspringuel** [comment]
@SirPL, it's generally better to open a new issue for this sort of thing.  Still, thanks for the report, should be fixed in #103.
